### ISSUE TITLE
Container startup failed due to java.io.FileNotFoundException

### ISSUE THREAD

**Issue by napramirez** [mesosphere/jenkins-dcos#106]
DC/OS Version:

```
{
  "version": "1.8.4",
  "dcos-image-commit": "e64024af95b62c632c90b9063ed06296fcf38ea5",
  "bootstrap-id": "5b4aa43610c57ee1d60b4aa0751a1fb75824c083"
}
```

Image: `mesosphere/jenkins:2.0.1-2.7.4`

Mesos stderr:

```
I0923 09:30:29.375962 18069 exec.cpp:161] Version: 1.0.1
I0923 09:30:29.385812 18083 exec.cpp:236] Executor registered on agent bbc3bdd8-a038-4ae3-ab58-7ed618c9718d-S5
I0923 09:30:29.388911 18083 docker.cpp:815] Running docker -H unix:///var/run/docker.sock run --cpu-shares 1024 --memory 2147483648 -e MARATHON_APP_LABEL_DCOS_PACKAGE_SOURCE=https://universe.mesosphere.com/repo -e LD_LIBRARY_PATH=/opt/mesosphere/lib -e MARATHON_APP_VERSION=2016-09-23T09:13:34.686Z -e HOST=192.168.100.123 -e MARATHON_APP_LABEL_MARATHON_SINGLE_INSTANCE_APP=true -e MARATHON_APP_RESOURCE_CPUS=1.0 -e MARATHON_APP_LABEL_DCOS_PACKAGE_REGISTRY_VERSION=2.0 -e SSH_KNOWN_HOSTS=github.com -e MARATHON_APP_LABEL_DCOS_SERVICE_SCHEME=http -e PORT_10102=17090 -e JENKINS_CONTEXT=/service/jenkins -e MARATHON_APP_RESOURCE_GPUS=0 -e MARATHON_APP_LABEL_DCOS_PACKAGE_RELEASE=13 -e JENKINS_AGENT_ROLE=* -e JVM_OPTS=-Xms1024m -Xmx1024m -e MARATHON_APP_LABEL_DCOS_SERVICE_NAME=jenkins -e MARATHON_APP_DOCKER_IMAGE=mesosphere/jenkins:2.0.1-2.7.4 -e MARATHON_APP_LABEL_DCOS_PACKAGE_NAME=jenkins -e MARATHON_APP_LABEL_DCOS_PACKAGE_VERSION=2.0.1-2.7.4 -e JENKINS_MESOS_MASTER=zk://leader.mesos:2181/mesos -e MESOS_TASK_ID=jenkins.5db5940c-8170-11e6-852e-70b3d5800001 -e PORT=17089 -e JENKINS_AGENT_USER=root -e MARATHON_APP_LABEL_DCOS_SERVICE_PORT_INDEX=0 -e MARATHON_APP_RESOURCE_MEM=2048.0 -e PORTS=17089,17090 -e PORT1=17090 -e JENKINS_OPTS= -e MARATHON_APP_LABEL_DCOS_PACKAGE_IS_FRAMEWORK=true -e PORT_10101=17089 -e MARATHON_APP_RESOURCE_DISK=0.0 -e MARATHON_APP_LABELS=DCOS_PACKAGE_RELEASE DCOS_SERVICE_SCHEME DCOS_PACKAGE_SOURCE DCOS_PACKAGE_REGISTRY_VERSION DCOS_SERVICE_NAME DCOS_PACKAGE_FRAMEWORK_NAME DCOS_SERVICE_PORT_INDEX DCOS_PACKAGE_VERSION DCOS_PACKAGE_NAME MARATHON_SINGLE_INSTANCE_APP DCOS_PACKAGE_IS_FRAMEWORK -e MARATHON_APP_LABEL_DCOS_PACKAGE_FRAMEWORK_NAME=jenkins -e JENKINS_FRAMEWORK_NAME=jenkins -e MARATHON_APP_ID=/jenkins -e PORT0=17089 -e LIBPROCESS_IP=192.168.100.123 -e MESOS_SANDBOX=/mnt/mesos/sandbox -e MESOS_CONTAINER_NAME=mesos-bbc3bdd8-a038-4ae3-ab58-7ed618c9718d-S5.337550bf-ad57-442e-8868-203d1450ac28 -v /tmp/jenkins:/var/jenkins_home:rw -v /opt/mesosphere:/opt/mesosphere:ro -v /var/lib/mesos/slave/slaves/bbc3bdd8-a038-4ae3-ab58-7ed618c9718d-S5/frameworks/5979eb78-ce69-475d-af3d-2c03d4af938c-0000/executors/jenkins.5db5940c-8170-11e6-852e-70b3d5800001/runs/337550bf-ad57-442e-8868-203d1450ac28:/mnt/mesos/sandbox --net host --name mesos-bbc3bdd8-a038-4ae3-ab58-7ed618c9718d-S5.337550bf-ad57-442e-8868-203d1450ac28 mesosphere/jenkins:2.0.1-2.7.4
nginx: /opt/mesosphere/lib/libcrypto.so.1.0.0: no version information available (required by nginx)
nginx: /opt/mesosphere/lib/libssl.so.1.0.0: no version information available (required by nginx)
nginx: /opt/mesosphere/lib/libssl.so.1.0.0: no version information available (required by nginx)
Sep 23, 2016 9:30:32 AM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Logging initialized @437ms
Sep 23, 2016 9:30:32 AM winstone.Logger logInternal
INFO: Beginning extraction from war file
Sep 23, 2016 9:30:32 AM winstone.Logger logInternal
INFO: Winstone shutdown successfully
Sep 23, 2016 9:30:32 AM winstone.Logger logInternal
SEVERE: Container startup failed
java.io.FileNotFoundException: /usr/share/jenkins/war/META-INF/MANIFEST.MF (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at winstone.HostConfiguration.getWebRoot(HostConfiguration.java:280)
    at winstone.HostConfiguration.<init>(HostConfiguration.java:83)
    at winstone.HostGroup.initHost(HostGroup.java:66)
    at winstone.HostGroup.<init>(HostGroup.java:45)
    at winstone.Launcher.<init>(Launcher.java:143)
    at winstone.Launcher.main(Launcher.java:352)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at Main._main(Main.java:246)
    at Main.main(Main.java:91)
```

**Comment by ssk2** [comment]
@napramirez: please share your operating system information and the options you used when installing Jenkins.

**Comment by napramirez** [comment]
OS: CentOS 7.2

Installation steps:
1. Go to Universe
2. Click Jenkins
3. Click Install

No options adjusted.

**Comment by 5h3rlock** [comment]
Experiencing same issues with same OS and same installation steps, @napramirez did you manage to resolve this issue yourself?

**Comment by ssk2** [comment]
@5h3rlock, @napramirez: I tried to replicate this and was able to install Jenkins without any issue. 

I'm using Centos 7.3:
```
[centos@ip-10-10-0-73 ~]$ rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64
```

This is using the latest version of the package (`2.1.0-2.19.3`) and DC/OS version 1.8.7. 

I'm going to close this for now but please re-open if you are still unable to get this working.
